// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://ejwjrsgkxxrwlyfohdat.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqd2pyc2dreHhyd2x5Zm9oZGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDQ4NTcsImV4cCI6MjA2OTEyMDg1N30.ayt6cFCW0m9uXbYV73yb-TusfcQehWzMQpP8t3eXqdg';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
